### ISSUE TITLE
[FEATURE] 프로젝트 폴더 구조 개선

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_front#12]
# ✅ 프로젝트 폴더 구조 개선

## ✏ TODO
- [x] 여러 페이지에서 사용하는 Memo 컴퍼넌트 공통 컴퍼넌트로 이동 후 이름 수정
- [x] 공통 컴퍼넌트 안에 memo, ui 폴더 생성 후 파일 위치
   - memo : memo interface를 사용하는 컴퍼넌트 위치(이 프로젝트에서만 재사용 가능)
   - ui : 프로젝트 내에 다른 상수, 파일에 의존하지 않는 컴퍼넌트 위치(다른 프로젝트에서 재사용 가능)
- [x] pages 폴더 만들고, 그 안에, AddPage, SearchPage 위치
- [x] 각 페이지 내에 컴퍼넌트 위치 수정

## ⏲ 예상 작업시간(선택)
4h
