### ISSUE TITLE
[FEATURE] 검색 화면 스크롤 기능 및 화면 업그레이드

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_front#14]
# ✅ 제목

## ✏ TODO
- [x] 스크롤 최신이 아닌 위치에 있어도, 질문을 하면, 자동으로 아래로 스크롤 하는 기능
- [x] 스크롤 끝이 아닌 다른 위치에 있으면, 아래로 스크롤하는 버튼 표시
- [x] 검색 내용을 입력하고, 엔터를 누르면, 자동 submit 기능 추가

### 나중에 추가한 것
- 검색창 디버깅 하다가 메모 자체에 색깔 없는 거 알게 되어 수정
- 검색 질문 내용에 줄바꿈이 화면에 적용 안되는 거 발견
   - css의 whitespace 설정 수정

## ⏲ 예상 작업시간(선택)
4h
