### ISSUE TITLE
[FEATURE] 검색 api 변경으로 인한 수정

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_front#20]
# ✅ 제목
검색 api 변경으로 인한 수정

## ✏ TODO
- [x] 자연어 대답이 화면에 보이게 코드 수정
- [x] 검색 대답이 현재 최소 width로 보이는 오류가 있는데, 글의 길이에 따라 바뀌도록 수정
- [x] 제대로 동작하는지 테스트

## 작업 branch
feature/NULL-126-change-search-memo

## 📖 참고 할만한 자료
검색 대답이 현재 최소 width로 보이는 오류 이미지(원래 width가 더 커야함)
![image](https://github.com/user-attachments/assets/d865b20e-1184-4e37-8601-0b9045aa19ec)

## ⏲ 예상 작업시간(선택)
2h
