### ISSUE TITLE
[FEATURE] 모바일 환경에서 사이드바 width 조절과 page 내부 padding 조절

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_front#22]
# ✅ 제목

## ✏ TODO
- [x] 모바일 화면
   - [x] 모바일 화면에서는 sidebar가 화면 위에 위치하게 수정
   - [x] sidebar를 열고 닫을 때, 앱 화면은 그대로, sidebar의 보여주는 화면의 width만 조절
   - [x] sidebar가 열렸을 때, 바깥 공간을 클릭하면, sidebar를 닫도록 구현
   - [x] padding 값 수정하기
- [x] 큰 화면
   - [x] 큰 화면에서는 sidebar가 화면 뒤에 위치하게 수정
   - [x] sidebar를 열고 닫을 때, sidebar의 보여주는 화면은 그대로, 앱 화면의 width만 조절
- [x] sidebar width를 0->특정 width로 변환해서 보여주던 애니메이션을 날라오는 애니메이션으로 변경

## branch
feature/NULL-160-mobile-sidebar-and-screen

## 구현 내용
https://feature-null-160-mobile-sidebar-and-screen.dwjzxct3xtdtj.amplifyapp.com/

## ⏲ 예상 작업시간(선택)
4h
