### ISSUE TITLE
[BUG] tag 입력, 수정 시 오류

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_front#34]
# 🚫 제목

## ✏ TODO
- [ ] enter가 안 막힘
- [ ] tab도 안 막힘
- [ ] 맨 마지막 단어에서 space 2번까지는 space 입력 가능한 오류
- [ ] 스페이스를 누르면 커서가 처음으로 가끔 가는데 재현을 못하겠음 -> 이건 몰루
- [ ] 탭 누르면 커서가 다음 태그 첫 글자로 감
- [ ] 태그를 수정하다가 다른 태그로 포커스를 옮기면(클릭하면) 기존 태그의 수정된 게 저장되어야 할 것 같음
