### ISSUE TITLE
[FEATURE] 메모 검색 화면 여러 디자인 후보로 구현해보기

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_front#36]
# ✅ 제목
메모 검색 화면 여러 디자인 후보로 구현해보기

## ✏ TODO
- [ ] 텍스트 입력란 한 개와 메모 검색 버튼, 메모 추가 버튼을 한개씩 구현
- [ ] 텍스트 입력란 2개와 메모 검색 버튼, 메모 추가 버튼
- [ ] 메모 검색 시, 이전 메모 검색 기록을 새로운 창에서 보여줌

**Comment by gee2450** [comment]
이 내용을 하기 전에, ux를 정하고, 디자인 맡겨서 해당 이슈 닫겠습니다.
